tasks 1-9
yoncho2001/p3csharp pull request #4
Opened 2023-08-07 14:30 UTC by yoncho2001

2023-08-08 11:48 UTC, GeorgiDyulgerov requested changes

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task1.cs
> +                double temp = number1;
Can you come up with another solution without a temp variable?

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task2.cs
> +
Unneeded new line. below also

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task3.cs
> +            switch (card)
Can you come up with another solution?  Write idea in comments.

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task5.cs
> +            double max = number1;
Can you give me another soloution

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task7.cs
> +            if (between > number3)
new line before another if block

2023-08-08 11:48 UTC, GeorgiDyulgerov commented on app3/task9.cs
> +            switch (input)
no default case?

2023-08-08 13:54 UTC, yoncho2001 commented on app3/task5.cs
> +            double max = number1;
i can't think for another way

2023-08-10 11:40 UTC, GeorgiDyulgerov approved these changes

2023-08-11 11:49 UTC, merged